# Generated by Django 6.0.4 on 2026-04-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='Grade',
            field=models.CharField(choices=[('12', '12'), ('11', '11'), ('10', '10'), ('9', '9')], max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('Grade', 'section'), name='unique_section_variant'),
        ),
    ]
