# Generated by Django 6.0.4 on 2026-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_classroom_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='unique',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=200, unique=True),
        ),
    ]
