# Generated by Django 6.0.4 on 2026-04-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sections_unique_section_variant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sections',
            name='unique_section_variant',
        ),
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('section', 'Grade'), name='unique_section_variant'),
        ),
    ]
