# Generated by Django 6.0.4 on 2026-04-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classroom_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='unique',
        ),
    ]
