# Generated by Django 6.0.4 on 2026-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_classroom_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='Grade',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
